/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.1.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 2019年8月23日
 ***********************************************************************************************/

#include "devicedetailedinformation_interface.h"

#define MAX_MASSAGE_SIZE 256

//
// Application state associated with this interface.
// It contains the DIGITALTWIN_INTERFACE_CLIENT_HANDLE used for responses in callbacks along with properties set
// and representations of the property update and command callbacks invoked on given interface
//
typedef struct DEVICEDETAILEDINFORMATION_INTERFACE_STATE_TAG
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceClientHandle;

} DEVICEDETAILEDINFORMATION_INTERFACE_STATE;

static DEVICEDETAILEDINFORMATION_INTERFACE_STATE appState;

// DeviceDetailedInformationInterface_PropertyCallback is invoked when a property is updated (or failed) going to server.
// ALL property callbacks will be routed to this function and just have the userContextCallback set to the propertyName.
// Product code will potentially have context stored in this userContextCallback.
static void DeviceDetailedInformationInterface_PropertyCallback(DIGITALTWIN_CLIENT_RESULT digitalTwinReportedStatus, void* userContextCallback)
{
    if (digitalTwinReportedStatus == DIGITALTWIN_CLIENT_OK)
    {
        ReportProperty_Succeeded_Callback("DeviceDetailedInformation", (const char*)userContextCallback);
        LogInfo("DEVICEDETAILEDINFORMATION_INTERFACE: Updating property=<%s> succeeded", (const char*)userContextCallback);
    }
    else
    {
        ReportProperty_Error_Callback("DeviceDetailedInformation", (const char*)userContextCallback);
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: Updating property=<%s> failed, error=<%s>", (const char*)userContextCallback, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, digitalTwinReportedStatus));
    }
}

// DeviceDetailedInformationInterface_ReportProperty_Internal is a helper function to report a DeviceDetailedInformation's properties.
// It invokes underlying DigitalTwin API for reporting properties and sets up its callback on completion.
DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_ReportProperty_Internal(DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle, const char* propertyName, const char* propertyData)
{
    DIGITALTWIN_CLIENT_RESULT result = DigitalTwin_InterfaceClient_ReportPropertyAsync(interfaceHandle, propertyName,
        (const char*)propertyData, NULL,
        DeviceDetailedInformationInterface_PropertyCallback, (void*)propertyName);

    if (result == DIGITALTWIN_CLIENT_OK)
    {
        LogInfo("DEVICEDETAILEDINFORMATION_INTERFACE: Queued async report read only property for %s", propertyName);
        
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: Reporting property=<%s> failed, error=<%s>", propertyName, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
    }

    DigitalTwinClientHelper_Check();
    return result;
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportDeviceName()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeDeviceNameProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_DeviceNameProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property DeviceName failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportAgentID()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeAgentIDProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_AgentIDProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property AgentID failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportDeviceGroups()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeDeviceGroupsProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_DeviceGroupsProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property DeviceGroups failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportWakeOnLAN()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeWakeOnLANProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_WakeOnLANProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property WakeOnLAN failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportConnectionStatus()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeConnectionStatusProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_ConnectionStatusProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property ConnectionStatus failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportAutoReport()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeAutoReportProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_AutoReportProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property AutoReport failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportStatusMessage()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeStatusMessageProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_StatusMessageProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property StatusMessage failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportProduct()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeProductProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_ProductProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property Product failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportManufacturer()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeManufacturerProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_ManufacturerProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property Manufacturer failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportVersion()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeVersionProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_VersionProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property Version failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportPlatform()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializePlatformProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_PlatformProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property Platform failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportOperatingSystem()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeOperatingSystemProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_OperatingSystemProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property OperatingSystem failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportMAC()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeMACProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_MACProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property MAC failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportCPU()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeCPUProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_CPUProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property CPU failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportMemory()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeMemoryProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_MemoryProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property Memory failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportGrafanaFolder()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeGrafanaFolderProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_GrafanaFolderProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property GrafanaFolder failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportGrafanaBoard()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeGrafanaBoardProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_GrafanaBoardProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property GrafanaBoard failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportLastConnectedAt()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before reporting properties");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (DeviceDetailedInformation_SerializeLastConnectedAtProperty(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return DeviceDetailedInformationInterface_ReportProperty_Internal(appState.interfaceClientHandle, DeviceDetailedInformationInterface_LastConnectedAtProperty, payloadBuffer);
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: serialize read only property LastConnectedAt failed");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT DeviceDetailedInformationInterface_Property_ReportAll()
{
    DIGITALTWIN_CLIENT_RESULT result;

    // NOTE: Future versions of SDK will support ability to send multiple properties in a single
    // send.  For now, one at a time is sufficient albeit less efficient.
    if (((result = DeviceDetailedInformationInterface_Property_ReportDeviceName()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportAgentID()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportDeviceGroups()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportWakeOnLAN()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportConnectionStatus()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportAutoReport()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportStatusMessage()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportProduct()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportManufacturer()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportVersion()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportPlatform()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportOperatingSystem()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportMAC()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportCPU()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportMemory()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportGrafanaFolder()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportGrafanaBoard()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = DeviceDetailedInformationInterface_Property_ReportLastConnectedAt()) != DIGITALTWIN_CLIENT_OK) )

    {
        LogError("DEVICE_INFO: Reporting properties failed.");
    }
    else
    {
        LogInfo("DEVICE_INFO: Queuing of all properties to be reported has succeeded");
    }

    return result;
}

// DeviceDetailedInformationInterface_InterfaceRegisteredCallback is invoked when this interface
// is successfully or unsuccessfully registered with the service, and also when the interface is deleted.
static void DeviceDetailedInformationInterface_InterfaceRegisteredCallback(DIGITALTWIN_CLIENT_RESULT dtInterfaceStatus, void* userInterfaceContext)
{
    LogInfo("DeviceDetailedInformationInterface_InterfaceRegisteredCallback with status=<%s>, userContext=<%p>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus), userInterfaceContext);
    if (dtInterfaceStatus == DIGITALTWIN_CLIENT_OK)
    {
        // Once the interface is registered, send our reported properties to the service.  
        // It *IS* safe to invoke most DigitalTwin API calls from a callback thread like this, though it 
        // is NOT safe to create/destroy/register interfaces now.
        LogInfo("DEVICEDETAILEDINFORMATION_INTERFACE: Interface successfully registered.");
    }
    else if (dtInterfaceStatus == DIGITALTWIN_CLIENT_ERROR_INTERFACE_UNREGISTERING)
    {
        // Once an interface is marked as unregistered, it cannot be used for any DigitalTwin SDK calls.
        LogInfo("DEVICEDETAILEDINFORMATION_INTERFACE: Interface received unregistering callback.");
    }
    else
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: Interface received failed, status=<%s>.", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus));
    }
}

//
// Create DigitalTwin interface client handle
//
DIGITALTWIN_INTERFACE_CLIENT_HANDLE DeviceDetailedInformationInterface_Create()
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle;
    DIGITALTWIN_CLIENT_RESULT result;

    memset(&appState, 0, sizeof(DEVICEDETAILEDINFORMATION_INTERFACE_STATE));

    if ((result = DigitalTwin_InterfaceClient_Create(DeviceDetailedInformationInterfaceId,  DeviceDetailedInformationInterfaceInstanceName, DeviceDetailedInformationInterface_InterfaceRegisteredCallback, (void*)&appState, &interfaceHandle)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("DEVICEDETAILEDINFORMATION_INTERFACE: Unable to allocate interface client handle for interfaceId=<%s>, interfaceInstanceName=<%s>, error=<%s>", DeviceDetailedInformationInterfaceId, DeviceDetailedInformationInterfaceInstanceName, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        interfaceHandle = NULL;
    }

    else
    {
        LogInfo("DEVICEDETAILEDINFORMATION_INTERFACE: Created DIGITALTWIN_INTERFACE_CLIENT_HANDLE successfully for interfaceId=<%s>, interfaceInstanceName=<%s>, handle=<%p>", DeviceDetailedInformationInterfaceId, DeviceDetailedInformationInterfaceInstanceName, interfaceHandle);
        appState.interfaceClientHandle = interfaceHandle;
    }

    return interfaceHandle;
}

void DeviceDetailedInformationInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle)
{
    // On shutdown, in general the first call made should be to DigitalTwin_InterfaceClient_Destroy.
    // This will block if there are any active callbacks in this interface, and then
    // mark the underlying handle such that no future callbacks shall come to it.
    DigitalTwin_InterfaceClient_Destroy(digitalTwinInterfaceClientHandle);

    // After DigitalTwin_InterfaceClient_Destroy returns, it is safe to assume
    // no more callbacks shall arrive for this interface and it is OK to free
    // resources callbacks otherwise may have needed.

}
