/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.1.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 2019年8月23日
 ***********************************************************************************************/

#ifndef DIGITALTWIN_SERIALIZER
#define DIGITALTWIN_SERIALIZER

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "azure_c_shared_utility/xlogging.h"
#include "parson.h"

#include "../AnCAD_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

bool SensorsInformation_SerializeRms_xTelemetry(char * payloadBuffer, int size);

bool SensorsInformation_SerializeRms_yTelemetry(char * payloadBuffer, int size);

bool SensorsInformation_SerializeMotor_speed_rpmTelemetry(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeDeviceNameProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeAgentIDProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeDeviceGroupsProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeWakeOnLANProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeConnectionStatusProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeAutoReportProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeStatusMessageProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeProductProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeManufacturerProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeVersionProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializePlatformProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeOperatingSystemProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeMACProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeCPUProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeMemoryProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeGrafanaFolderProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeGrafanaBoardProperty(char * payloadBuffer, int size);

bool DeviceDetailedInformation_SerializeLastConnectedAtProperty(char * payloadBuffer, int size);

bool DeviceInfo_SerializeManufacturerProperty(char * payloadBuffer, int size);

bool DeviceInfo_SerializeModelProperty(char * payloadBuffer, int size);

bool DeviceInfo_SerializeSwVersionProperty(char * payloadBuffer, int size);

bool DeviceInfo_SerializeOsNameProperty(char * payloadBuffer, int size);

bool DeviceInfo_SerializeProcessorArchitectureProperty(char * payloadBuffer, int size);

bool DeviceInfo_SerializeProcessorManufacturerProperty(char * payloadBuffer, int size);

bool DeviceInfo_SerializeTotalStorageProperty(char * payloadBuffer, int size);

bool DeviceInfo_SerializeTotalMemoryProperty(char * payloadBuffer, int size);

#ifdef __cplusplus
}
#endif

#endif // DIGITALTWIN_SERIALIZER
