/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.1.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 2019年8月23日
 ***********************************************************************************************/

#include "digitaltwin_serializer.h"

//
// Serialize telemetry data
//

bool SensorsInformation_SerializeRms_xTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double rms_x = SensorsInformation_Telemetry_ReadRms_x();

    int neededSize = snprintf(NULL, 0, "%f", rms_x);

    if (neededSize > size - 1)
    {
        LogError("Failed to build rms_x payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", rms_x);
    }

    return true;
}

bool SensorsInformation_SerializeRms_yTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double rms_y = SensorsInformation_Telemetry_ReadRms_y();

    int neededSize = snprintf(NULL, 0, "%f", rms_y);

    if (neededSize > size - 1)
    {
        LogError("Failed to build rms_y payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", rms_y);
    }

    return true;
}

bool SensorsInformation_SerializeMotor_speed_rpmTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double motor_speed_rpm = SensorsInformation_Telemetry_ReadMotor_speed_rpm();

    int neededSize = snprintf(NULL, 0, "%f", motor_speed_rpm);

    if (neededSize > size - 1)
    {
        LogError("Failed to build motor_speed_rpm payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", motor_speed_rpm);
    }

    return true;
}

//
// Serialize read-only property
//

bool DeviceDetailedInformation_SerializeDeviceNameProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* deviceName = DeviceDetailedInformation_Property_GetDeviceName();

    int neededSize = snprintf(NULL, 0, "\"%s\"", deviceName);

    if (neededSize > size - 1)
    {
        LogError("Failed to build DeviceName payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", deviceName);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeAgentIDProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* agentID = DeviceDetailedInformation_Property_GetAgentID();

    int neededSize = snprintf(NULL, 0, "\"%s\"", agentID);

    if (neededSize > size - 1)
    {
        LogError("Failed to build AgentID payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", agentID);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeDeviceGroupsProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* deviceGroups = DeviceDetailedInformation_Property_GetDeviceGroups();

    int neededSize = snprintf(NULL, 0, "\"%s\"", deviceGroups);

    if (neededSize > size - 1)
    {
        LogError("Failed to build DeviceGroups payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", deviceGroups);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeWakeOnLANProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* wakeOnLAN = DeviceDetailedInformation_Property_GetWakeOnLAN();

    int neededSize = snprintf(NULL, 0, "\"%s\"", wakeOnLAN);

    if (neededSize > size - 1)
    {
        LogError("Failed to build WakeOnLAN payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", wakeOnLAN);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeConnectionStatusProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* connectionStatus = DeviceDetailedInformation_Property_GetConnectionStatus();

    int neededSize = snprintf(NULL, 0, "\"%s\"", connectionStatus);

    if (neededSize > size - 1)
    {
        LogError("Failed to build ConnectionStatus payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", connectionStatus);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeAutoReportProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* autoReport = DeviceDetailedInformation_Property_GetAutoReport();

    int neededSize = snprintf(NULL, 0, "\"%s\"", autoReport);

    if (neededSize > size - 1)
    {
        LogError("Failed to build AutoReport payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", autoReport);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeStatusMessageProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* statusMessage = DeviceDetailedInformation_Property_GetStatusMessage();

    int neededSize = snprintf(NULL, 0, "\"%s\"", statusMessage);

    if (neededSize > size - 1)
    {
        LogError("Failed to build StatusMessage payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", statusMessage);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeProductProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* product = DeviceDetailedInformation_Property_GetProduct();

    int neededSize = snprintf(NULL, 0, "\"%s\"", product);

    if (neededSize > size - 1)
    {
        LogError("Failed to build Product payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", product);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeManufacturerProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* manufacturer = DeviceDetailedInformation_Property_GetManufacturer();

    int neededSize = snprintf(NULL, 0, "\"%s\"", manufacturer);

    if (neededSize > size - 1)
    {
        LogError("Failed to build Manufacturer payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", manufacturer);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeVersionProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* version = DeviceDetailedInformation_Property_GetVersion();

    int neededSize = snprintf(NULL, 0, "\"%s\"", version);

    if (neededSize > size - 1)
    {
        LogError("Failed to build Version payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", version);
    }

    return true;
}

bool DeviceDetailedInformation_SerializePlatformProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* platform = DeviceDetailedInformation_Property_GetPlatform();

    int neededSize = snprintf(NULL, 0, "\"%s\"", platform);

    if (neededSize > size - 1)
    {
        LogError("Failed to build Platform payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", platform);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeOperatingSystemProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* operatingSystem = DeviceDetailedInformation_Property_GetOperatingSystem();

    int neededSize = snprintf(NULL, 0, "\"%s\"", operatingSystem);

    if (neededSize > size - 1)
    {
        LogError("Failed to build OperatingSystem payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", operatingSystem);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeMACProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* mAC = DeviceDetailedInformation_Property_GetMAC();

    int neededSize = snprintf(NULL, 0, "\"%s\"", mAC);

    if (neededSize > size - 1)
    {
        LogError("Failed to build MAC payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", mAC);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeCPUProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* cPU = DeviceDetailedInformation_Property_GetCPU();

    int neededSize = snprintf(NULL, 0, "\"%s\"", cPU);

    if (neededSize > size - 1)
    {
        LogError("Failed to build CPU payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", cPU);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeMemoryProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    int memory = DeviceDetailedInformation_Property_GetMemory();

    int neededSize = snprintf(NULL, 0, "%d", memory);

    if (neededSize > size - 1)
    {
        LogError("Failed to build Memory payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%d", memory);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeGrafanaFolderProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* grafanaFolder = DeviceDetailedInformation_Property_GetGrafanaFolder();

    int neededSize = snprintf(NULL, 0, "\"%s\"", grafanaFolder);

    if (neededSize > size - 1)
    {
        LogError("Failed to build GrafanaFolder payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", grafanaFolder);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeGrafanaBoardProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* grafanaBoard = DeviceDetailedInformation_Property_GetGrafanaBoard();

    int neededSize = snprintf(NULL, 0, "\"%s\"", grafanaBoard);

    if (neededSize > size - 1)
    {
        LogError("Failed to build GrafanaBoard payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", grafanaBoard);
    }

    return true;
}

bool DeviceDetailedInformation_SerializeLastConnectedAtProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* lastConnectedAt = DeviceDetailedInformation_Property_GetLastConnectedAt();

    int neededSize = snprintf(NULL, 0, "\"%s\"", lastConnectedAt);

    if (neededSize > size - 1)
    {
        LogError("Failed to build LastConnectedAt payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", lastConnectedAt);
    }

    return true;
}

bool DeviceInfo_SerializeManufacturerProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* manufacturer = DeviceInfo_Property_GetManufacturer();

    int neededSize = snprintf(NULL, 0, "\"%s\"", manufacturer);

    if (neededSize > size - 1)
    {
        LogError("Failed to build manufacturer payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", manufacturer);
    }

    return true;
}

bool DeviceInfo_SerializeModelProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* model = DeviceInfo_Property_GetModel();

    int neededSize = snprintf(NULL, 0, "\"%s\"", model);

    if (neededSize > size - 1)
    {
        LogError("Failed to build model payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", model);
    }

    return true;
}

bool DeviceInfo_SerializeSwVersionProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* swVersion = DeviceInfo_Property_GetSwVersion();

    int neededSize = snprintf(NULL, 0, "\"%s\"", swVersion);

    if (neededSize > size - 1)
    {
        LogError("Failed to build swVersion payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", swVersion);
    }

    return true;
}

bool DeviceInfo_SerializeOsNameProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* osName = DeviceInfo_Property_GetOsName();

    int neededSize = snprintf(NULL, 0, "\"%s\"", osName);

    if (neededSize > size - 1)
    {
        LogError("Failed to build osName payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", osName);
    }

    return true;
}

bool DeviceInfo_SerializeProcessorArchitectureProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* processorArchitecture = DeviceInfo_Property_GetProcessorArchitecture();

    int neededSize = snprintf(NULL, 0, "\"%s\"", processorArchitecture);

    if (neededSize > size - 1)
    {
        LogError("Failed to build processorArchitecture payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", processorArchitecture);
    }

    return true;
}

bool DeviceInfo_SerializeProcessorManufacturerProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* processorManufacturer = DeviceInfo_Property_GetProcessorManufacturer();

    int neededSize = snprintf(NULL, 0, "\"%s\"", processorManufacturer);

    if (neededSize > size - 1)
    {
        LogError("Failed to build processorManufacturer payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", processorManufacturer);
    }

    return true;
}

bool DeviceInfo_SerializeTotalStorageProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long totalStorage = DeviceInfo_Property_GetTotalStorage();

    int neededSize = snprintf(NULL, 0, "%ld", totalStorage);

    if (neededSize > size - 1)
    {
        LogError("Failed to build totalStorage payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", totalStorage);
    }

    return true;
}

bool DeviceInfo_SerializeTotalMemoryProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long totalMemory = DeviceInfo_Property_GetTotalMemory();

    int neededSize = snprintf(NULL, 0, "%ld", totalMemory);

    if (neededSize > size - 1)
    {
        LogError("Failed to build totalMemory payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", totalMemory);
    }

    return true;
}

