/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.1.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 2019年8月23日
 ***********************************************************************************************/

#include "sensorsinformation_interface.h"

#define MAX_MASSAGE_SIZE 256

//
// Application state associated with this interface.
// It contains the DIGITALTWIN_INTERFACE_CLIENT_HANDLE used for responses in callbacks along with properties set
// and representations of the property update and command callbacks invoked on given interface
//
typedef struct SENSORSINFORMATION_INTERFACE_STATE_TAG
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceClientHandle;

} SENSORSINFORMATION_INTERFACE_STATE;

static SENSORSINFORMATION_INTERFACE_STATE appState;

// SensorsInformationInterface_TelemetryCallback is invoked when a DigitalTwin telemetry message is either successfully delivered to the service or else fails.
static void SensorsInformationInterface_TelemetryCallback(DIGITALTWIN_CLIENT_RESULT digitalTwinTelemetryStatus, void* userContextCallback)
{
    if (digitalTwinTelemetryStatus == DIGITALTWIN_CLIENT_OK)
    {
        SendTelemetry_Succeeded_Callback("SensorsInformation", (const char*)userContextCallback);
        LogInfo("SENSORSINFORMATION_INTERFACE: DigitalTwin successfully delivered telemetry message for <%s>", (const char*)userContextCallback);
    }
    else
    {
        SendTelemetry_Error_Callback("SensorsInformation", (const char*)userContextCallback);
        LogError("SENSORSINFORMATION_INTERFACE: DigitalTwin failed to deliver telemetry message for <%s>, error=<%s> ", (const char*)userContextCallback, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, digitalTwinTelemetryStatus));
    }
}

// SendTelemetry is a helper function which is periodically invoked by the caller to send telemetry
DIGITALTWIN_CLIENT_RESULT SensorsInformationInterface_SendTelemetry_Internal(DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle, const char* telemetryName, const char* telemetryData)
{
    DIGITALTWIN_CLIENT_RESULT result;

    result = DigitalTwin_InterfaceClient_SendTelemetryAsync(interfaceHandle, telemetryName, telemetryData,
        SensorsInformationInterface_TelemetryCallback, (void*)telemetryName);

    if (result != DIGITALTWIN_CLIENT_OK)
    {
        LogError("SENSORSINFORMATION_INTERFACE:: DigitalTwin_InterfaceClient_SendTelemetryAsync failed for sending %s", telemetryName);
    }
    else
    {
        LogInfo("SENSORSINFORMATION_INTERFACE:: DigitalTwin_InterfaceClient_SendTelemetryAsync successfully sent %s", telemetryName);
    }

    DigitalTwinClientHelper_Check();
    return result;
}

DIGITALTWIN_CLIENT_RESULT SensorsInformationInterface_Telemetry_SendAll()
{
    DIGITALTWIN_CLIENT_RESULT result;

    // NOTE: Future versions of SDK will support ability to send multiple telemetries in a single
    // send.  For now, one at a time is sufficient albeit less efficient.
    if (((result = SensorsInformationInterface_Telemetry_SendRms_x()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = SensorsInformationInterface_Telemetry_SendRms_y()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = SensorsInformationInterface_Telemetry_SendMotor_speed_rpm()) != DIGITALTWIN_CLIENT_OK) )

    {
        LogError("SENSORSINFORMATION_INTERFACE: failed to send telemetries");
    }
    else
    {
        LogInfo("SENSORSINFORMATION_INTERFACE: Queuing of all telemetries to be sent has succeeded");
    }

    return result;
}

DIGITALTWIN_CLIENT_RESULT SensorsInformationInterface_Telemetry_SendRms_x()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORSINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (SensorsInformation_SerializeRms_xTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return SensorsInformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, SensorsInformationInterface_Rms_xTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORSINFORMATION_INTERFACE: serialize telemetry message rms_x failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT SensorsInformationInterface_Telemetry_SendRms_y()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORSINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (SensorsInformation_SerializeRms_yTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return SensorsInformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, SensorsInformationInterface_Rms_yTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORSINFORMATION_INTERFACE: serialize telemetry message rms_y failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT SensorsInformationInterface_Telemetry_SendMotor_speed_rpm()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("SENSORSINFORMATION_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (SensorsInformation_SerializeMotor_speed_rpmTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return SensorsInformationInterface_SendTelemetry_Internal(appState.interfaceClientHandle, SensorsInformationInterface_Motor_speed_rpmTelemetry, payloadBuffer);
    }
    else
    {
        LogError("SENSORSINFORMATION_INTERFACE: serialize telemetry message motor_speed_rpm failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

// SensorsInformationInterface_InterfaceRegisteredCallback is invoked when this interface
// is successfully or unsuccessfully registered with the service, and also when the interface is deleted.
static void SensorsInformationInterface_InterfaceRegisteredCallback(DIGITALTWIN_CLIENT_RESULT dtInterfaceStatus, void* userInterfaceContext)
{
    LogInfo("SensorsInformationInterface_InterfaceRegisteredCallback with status=<%s>, userContext=<%p>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus), userInterfaceContext);
    if (dtInterfaceStatus == DIGITALTWIN_CLIENT_OK)
    {
        // Once the interface is registered, send our reported properties to the service.  
        // It *IS* safe to invoke most DigitalTwin API calls from a callback thread like this, though it 
        // is NOT safe to create/destroy/register interfaces now.
        LogInfo("SENSORSINFORMATION_INTERFACE: Interface successfully registered.");
    }
    else if (dtInterfaceStatus == DIGITALTWIN_CLIENT_ERROR_INTERFACE_UNREGISTERING)
    {
        // Once an interface is marked as unregistered, it cannot be used for any DigitalTwin SDK calls.
        LogInfo("SENSORSINFORMATION_INTERFACE: Interface received unregistering callback.");
    }
    else
    {
        LogError("SENSORSINFORMATION_INTERFACE: Interface received failed, status=<%s>.", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus));
    }
}

//
// Create DigitalTwin interface client handle
//
DIGITALTWIN_INTERFACE_CLIENT_HANDLE SensorsInformationInterface_Create()
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle;
    DIGITALTWIN_CLIENT_RESULT result;

    memset(&appState, 0, sizeof(SENSORSINFORMATION_INTERFACE_STATE));

    if ((result = DigitalTwin_InterfaceClient_Create(SensorsInformationInterfaceId,  SensorsInformationInterfaceInstanceName, SensorsInformationInterface_InterfaceRegisteredCallback, (void*)&appState, &interfaceHandle)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("SENSORSINFORMATION_INTERFACE: Unable to allocate interface client handle for interfaceId=<%s>, interfaceInstanceName=<%s>, error=<%s>", SensorsInformationInterfaceId, SensorsInformationInterfaceInstanceName, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        interfaceHandle = NULL;
    }

    else
    {
        LogInfo("SENSORSINFORMATION_INTERFACE: Created DIGITALTWIN_INTERFACE_CLIENT_HANDLE successfully for interfaceId=<%s>, interfaceInstanceName=<%s>, handle=<%p>", SensorsInformationInterfaceId, SensorsInformationInterfaceInstanceName, interfaceHandle);
        appState.interfaceClientHandle = interfaceHandle;
    }

    return interfaceHandle;
}

void SensorsInformationInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle)
{
    // On shutdown, in general the first call made should be to DigitalTwin_InterfaceClient_Destroy.
    // This will block if there are any active callbacks in this interface, and then
    // mark the underlying handle such that no future callbacks shall come to it.
    DigitalTwin_InterfaceClient_Destroy(digitalTwinInterfaceClientHandle);

    // After DigitalTwin_InterfaceClient_Destroy returns, it is safe to assume
    // no more callbacks shall arrive for this interface and it is OK to free
    // resources callbacks otherwise may have needed.

}
