/*******************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.1.
 *
 * You need to add your implementation here to:
 *    - get telemetry data from device/sensor
 *    - set read-only property data
 *    - handle read-write property callback
 *    - process device command
 *
 * Generated Date: 2019年8月23日
 *******************************************************************************************/

#include "AnCAD_impl.h"
#include "utilities/digitaltwin_serializer.h"
#include "utilities/devicedetailedinformation_interface.h"
#include "utilities/sensorsinformation_interface.h"
#include "utilities/deviceinfo_interface.h"
#include "SensorSources.h"
#include "SensorCallback.h"

#define Payload_Buffer_Size 256

char *gLastConnectedAt = NULL;

double SensorsInformation_Telemetry_ReadRms_x()
{
    // TODO: provide implementation here
	StartMqttSneakLoop(CallBack_SensorData, NULL);
    return Get_rms_x();
}

double SensorsInformation_Telemetry_ReadRms_y()
{
    // TODO: provide implementation here
	StartMqttSneakLoop(CallBack_SensorData, NULL);
    return Get_rms_y();
}

double SensorsInformation_Telemetry_ReadMotor_speed_rpm()
{
    // TODO: provide implementation here
	StartMqttSneakLoop(CallBack_SensorData, NULL);
    return Get_motor_speed_rpm();
}

void SendTelemetry_Succeeded_Callback(const char* interfaceName, const char* telemetryName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on success.

    LogInfo("DigitalTwin successfully delivered telemetry message for %s::%s", interfaceName, telemetryName);
}

void SendTelemetry_Error_Callback(const char* interfaceName, const char* telemetryName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on failure.

    LogInfo("DigitalTwin failed to deliver telemetry message for %s::%s", interfaceName, telemetryName);
}

void ReportProperty_Succeeded_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback reporting property on success.

    LogInfo("DigitalTwin successfully report writable property for %s::%s", interfaceName, propertyName);
}

void ReportProperty_Error_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback of reporting property on failure.

    LogInfo("DigitalTwin failed to report writable property for %s::%s", interfaceName, propertyName);
}

char* DeviceDetailedInformation_Property_GetDeviceName()
{
    // TODO: provide implementation here
    return "DESKTOP-ABC";
}

char* DeviceDetailedInformation_Property_GetAgentID()
{
    // TODO: provide implementation here
    return "demo";
}

char* DeviceDetailedInformation_Property_GetDeviceGroups()
{
    // TODO: provide implementation here
    return "Demo, Default, Default";
}

char* DeviceDetailedInformation_Property_GetWakeOnLAN()
{
    // TODO: provide implementation here
    return "Not Set";
}

char* DeviceDetailedInformation_Property_GetConnectionStatus()
{
    // TODO: provide implementation here
    return "Connected";
}

char* DeviceDetailedInformation_Property_GetAutoReport()
{
    // TODO: provide implementation here
    return "ON";
}

char* DeviceDetailedInformation_Property_GetStatusMessage()
{
    // TODO: provide implementation here
    return "None";
}

char* DeviceDetailedInformation_Property_GetProduct()
{
    // TODO: provide implementation here
    return "WISE-Agent";
}

char* DeviceDetailedInformation_Property_GetManufacturer()
{
    // TODO: provide implementation here
    return "Advantech";
}

char* DeviceDetailedInformation_Property_GetVersion()
{
    // TODO: provide implementation here
    return "1.2.5.0";
}

char* DeviceDetailedInformation_Property_GetPlatform()
{
    // TODO: provide implementation here
    return "ARK-2250";
}

char* DeviceDetailedInformation_Property_GetOperatingSystem()
{
    // TODO: provide implementation here
    return "Windows 10 Enterprise 2016 LTSB X64";
}

char* DeviceDetailedInformation_Property_GetMAC()
{
    // TODO: provide implementation here
    return "demo";
}

char* DeviceDetailedInformation_Property_GetCPU()
{
    // TODO: provide implementation here
    return "Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz";
}

int DeviceDetailedInformation_Property_GetMemory()
{
    // TODO: provide implementation here
    return 8294028;
}

char* DeviceDetailedInformation_Property_GetGrafanaFolder()
{
    // TODO: provide implementation here
    return "(empty)";
}

char* DeviceDetailedInformation_Property_GetGrafanaBoard()
{
    // TODO: provide implementation here
    return "(empty)";
}

char* DeviceDetailedInformation_Property_GetLastConnectedAt()
{
    // TODO: provide implementation here

    if(gLastConnectedAt == NULL) {
        time_t rawtime;
        struct tm *info;
        char buffer[80];

        time( &rawtime );
        info = localtime( &rawtime );

        strftime(buffer,80,"%Y-%m-%dT%H:%M:%S", info);
        gLastConnectedAt = _strdup(buffer);
    }

    return gLastConnectedAt;
}

char* DeviceInfo_Property_GetManufacturer()
{
    // TODO: provide implementation here
    return "Advantech";
}

char* DeviceInfo_Property_GetModel()
{
    // TODO: provide implementation here
    return "ARK-2250";
}

char* DeviceInfo_Property_GetSwVersion()
{
    // TODO: provide implementation here
    return "1.2.5.0";
}

char* DeviceInfo_Property_GetOsName()
{
    // TODO: provide implementation here
    return "Windows 10 Enterprise 2016 LTSB X64";
}

char* DeviceInfo_Property_GetProcessorArchitecture()
{
    // TODO: provide implementation here
    return "Core(TM) i5-6300U CPU @ 2.40GHz";
}

char* DeviceInfo_Property_GetProcessorManufacturer()
{
    // TODO: provide implementation here
    return "Intel";
}

long DeviceInfo_Property_GetTotalStorage()
{
    // TODO: provide implementation here
    return 0L;
}

long DeviceInfo_Property_GetTotalMemory()
{
    // TODO: provide implementation here
    return 0L;
}

